version: '3.8'

services:
  db:
    image: mariadb:10.8.3
    container_name: moodle-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: root
      MYSQL_PASSWORD: rootpass
    volumes:
      - ./data/db:/var/lib/mysql
    networks:
      - moodle-net

  moodle:
    build: ./docker/moodle
    container_name: moodle-app
    restart: always
    depends_on:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./wwwroot:/var/www/html
      - ./data/moodledata:/var/moodledata
    networks:
      - moodle-net

networks:
  moodle-net:
    driver: bridge
